name: "test-local"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - run: npm ci
    - uses: ./
      with:
        elm-version: 0.19.1
